name: hada
channels:
  - conda-forge
dependencies:
  - xarray
  - rioxarray
  - tiledb=2.11  # needed by rioxarray
  - netcdf4
  - click
  - tqdm
  - coloredlogs
  - pytest
  - toml
  - pyproj
  - matplotlib
  - cartopy
  - shapely
  - dask
