# The variables to read. Unless variables are specified for a reader, then all variables listed
# here are acquired. Variable names should be specified in CF-standard names.
variables = [
  "x_wind",
  # "y_wind",
]

# Prioritized list of datasets
[datasets.norkyst]
url = "https://thredds.met.no/thredds/dodsC/sea/norkyst800m/1h/aggregate_be"

# https://thredds.met.no/thredds/dodsC/mepslatest/meps_lagged_6_h_latest_2_5km_latest.nc
# https://thredds.met.no/thredds/dodsC/fou-hi/barents_eps_zdepth_be
# https://thredds.met.no/thredds/dodsC/cmems/mywavewam3km/dataset-wam-arctic-1hr3km-be.ncml
# https://thredds.met.no/thredds/dodsC/cmems/topaz6/dataset-topaz6-arc-15min-3km-be.ncml
