# Få ut alle variabler i sammenstilt netcdf fra flere datakilder (Norkyst, MEPS, Barents)?
# [X] Vindhastighet (m/s)
# [X] Lufttemperatur (celsius grader)
# [X] Sjøtemperatur (celsius grader)
# [X] Signifikant bølgehøyde (m)
# [X] (Iskonsentrasjon (fraksjon))
# [X] Sikt (0/1)*
# [X] Strømhastighet
# [X] Disse er sammenstilt til felles tidssteg for hver time i forcast perioden.
# [X] Projeksjon: endre til EPSG 3575
# [X] Bbox input angis i meter i denne epsg
# [X] XOutput netcdf blir i denne epsg
# [X] Output Grid er 800x800 meter cellestørrelse fast.

# Scalar variables
scalar_variables = [
  'air_temperature',
  'sea_temperature',
  'ice_concentration',
  'significant_wave_height',
]

# Argument order must match input to calculating function.
[derived_variables]
horizontal_visibility = [ 'relative_humidity', 'fog' ]

# Vector variables to read into a single magnitude scalar field.
[vector_magnitude_variables]
wind = ["x_wind", "y_wind"]
current = ["x_sea_water", "y_sea_water"]

# Prioritized list of datasets
[datasets.norkyst]
url = "https://thredds.met.no/thredds/dodsC/sea/norkyst800m/1h/aggregate_be"
x = 'X'
y = 'Y'

[datasets.norkyst.variables]
sea_temperature = 'temperature'
x_wind = 'Uwind'
y_wind = 'Vwind'
x_sea_water = 'u'
y_sea_water = 'v'

[datasets.barents]
url = "https://thredds.met.no/thredds/dodsC/fou-hi/barents_eps_zdepth_be"
x = 'X'
y = 'Y'

[datasets.barents.variables]
ice_concentration = 'ice_concentration'
x_sea_water = 'u'
y_sea_water = 'v'
sea_temperature = 'temperature'
x_wind = 'Uwind'
y_wind = 'Vwind'

[datasets.mywavewam4]
url = 'https://thredds.met.no/thredds/dodsC/sea/mywavewam4/mywavewam4_be'
x = 'rlon'
y = 'rlat'

[datasets.mywavewam4.variables]
significant_wave_height = 'hs'

[datasets.meps]
url = "https://thredds.met.no/thredds/dodsC/mepslatest/meps_lagged_6_h_latest_2_5km_latest.nc"
x = 'x'
y = 'y'

[datasets.meps.variables]
air_temperature = 'air_temperature_2m'
x_wind = 'x_wind_10m'
y_wind = 'y_wind_10m'
relative_humidity = 'relative_humidity_2m'
fog = 'fog_area_fraction'

# https://thredds.met.no/thredds/dodsC/cmems/topaz6/dataset-topaz6-arc-15min-3km-be.ncml
